package com.hedgehogkb.fighter.moves;

public enum MoveType {
    STANDING, IDLE, FALLING, STUNNED, DOWNED, CROUCHING, SHIELDING,
    CROUCH_WALKING, WALKING, SPRINTING, JUMPING,
    NORMAL_ATTACK, FORWARD_ATTACK, UP_ATTACK, DOWN_ATTACK,
    NAIR_ATTACK, FAIR_ATTACK, UAIR_ATTACK, DAIR_ATTACK,
    NORMAL_SPECIAL, FORWARD_SPECIAL, UP_SPECIAL, DOWN_SPECIAL
}
